### PR TITLE
Added PHP 7.3.4, 7.2.17, 7.1.28

### PR DESCRIPTION
**Pull request by kunit**

### CODE REVIEW

**Comment by ottlinger** [comment]
Thanks for your contribution, as long as https://github.com/php-build/php-build/issues/565 is not solved there is no chance of getting newer versions :(

**Comment by GrahamCampbell** [comment]
@kunit Thanks for the PR. Merging. :)

@ottlinger I'm not sure why that other issue affecting PHP 5.2 would be blocking this?

**Comment by ottlinger** [comment]
@GrahamCampbell as long as the build is not green, upstream services such as Travis are unable to grab newer versions. That's what I meant with "there is no chane of getting newer PHP versions".

**Comment by GrahamCampbell** [comment]
> as long as the build is not green, upstream services such as Travis are unable to grab newer versions

Why not?

**Comment by ottlinger** [comment]
@GrahamCampbell upstream services like Travis rely on a green build in order to take artefacts into accounts php-build generates. As the build is red due to the 5.x problems it's not possible to use the new versions on Travis.

**Comment by GrahamCampbell** [comment]
Really. Travis certainly used to manually just pick the commit they wanted from phpbuild. I've sent them upgrade PRs in the past, but maybe they have changed it since. Do you have a link to their new code?

**Comment by ottlinger** [comment]
@GrahamCampbell I'm unable to point you to any Travis repo, but I see regular build failures when I try to enable versions that are merged into php-build/master - therefore I filed the PR to temporarily disable the problematic 5.x version in order to make all the other versions available .....

Here's a link to a failing build:
https://travis-ci.org/ottlinger/hornherzogen/jobs/516512270

**Comment by GrahamCampbell** [comment]
I think that's just because they have not manually updated yet.

**Comment by ottlinger** [comment]
@GrahamCampbell Older versions are not picked up as well:
https://travis-ci.org/ottlinger/hornherzogen/jobs/516966991
as the build is not green, no new(er) versions are picked up.

**Pull request merged**
