### PR TITLE
:memo: readme and changelog

### PR DESCRIPTION
**Pull request by gerardroche**
- Cleanup readme
- Move changelog into its own file

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Wondering if we should just delete the change log?

**Comment by gerardroche** [comment]
No, a changelog is nice to have. I'm going to add a format style for them:

## x.x.x

### Bug Fixes

- item

### Changes

- item

### New Features

- item

## x.x.x

### Bug Fixes

- item

### Changes

- item

### New Features

- item


...

**Comment by GrahamCampbell** [comment]
> No, a changelog is nice to have.

It's really out of date though.

**Comment by gerardroche** [comment]
We could start fresh for 1.0.0.

**Comment by GrahamCampbell** [comment]
> We could start afresh for 1.0.0.

Maybe, yeh. // cc @php-build/owners

**Comment by rogeriopradoj** [comment]
Looks awesome to me!

About the changelog, I think we could separate it right now as suggested, and filling missing parts before too long!

> We could start afresh for 1.0.0.

I prefer if we could catch the missing parts, even if after 1.0.0 release time.

> [...]  a changelog is nice to have.

Totally agreed. I think it could be a good idea to change `CONTRIBUTING.md` to inform that the Pull Request should come with an entering to CHANGELOG, what do you say?

**Comment by gerardroche** [comment]
> Totally agreed. I think it could be a good idea to change CONTRIBUTING.md to inform that the Pull Request should come with an entering to CHANGELOG, what do you say? 

:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Updating this change log might take a while though, lol.

**Comment by gerardroche** [comment]
I think only changes relevant to the user need to go in the changelog.  For example, does this pr change need to go in the changelog? Probably not. The changelog is a kind-of requires-attention/fix-all-the-things/useful-to-know log. Sometimes you see logs with "fixes", and "refactorings", or my favourite, "stuff", the user doesn't need to know this, those kind of logs are even useless to developers.  

Also, I think adding credits ala *Thanks to @...`* in the messages is maybe too much. There is a [contributors graph](https://github.com/php-build/php-build/graphs/contributors) and commit logs.

**Comment by gerardroche** [comment]
Keep a changelog: http://keepachangelog.com/

**Comment by GrahamCampbell** [comment]
> Keep a changelog: http://keepachangelog.com/

I'm not really a fan of that tbh. I think it would make sense for us to organise it our own way.

**Comment by gerardroche** [comment]
I'm not entirely a fan myself. It has some good ideas.

**Comment by gerardroche** [comment]
Can we merge this so that we can start cleaning up the changelog file and start keeping it up to date?

**Pull request merged**
