### PR TITLE
PHP updates

### PR DESCRIPTION
**Pull request by mlocher**
* 5.4.41
* 5.6.9

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What about 5.5?

**Comment by GrahamCampbell** [comment]
I already had this change done locally. Just waiting until the releases were actually propagated before committing and pushing. Thank you anyway though. :)

**Comment by mlocher** [comment]
Wasn't released yet, when I opened the PR, I'll push a new commit for 5.5 later today!

**Comment by GrahamCampbell** [comment]
Already done.

**Comment by GrahamCampbell** [comment]
That's why we didn't commit these new releases earlier. I always wait until all 3 releases are done before doing this.

**Comment by mlocher** [comment]
Ok, good to know, thx!

**Comment by CHH** [comment]
Thank you @mlocher and @GrahamCampbell!

**Comment by rogeriopradoj** [comment]
Hi, @CHH, @loicfrering and @GrahamCampbell, I know maybe it's not the best place to put it, anyway have you taken a look at https://github.com/php-build/php-build/wiki/phpenv%20tools?

**Pull request closed without merging**
