### PR TITLE
Added php 5.4.40, 5.5.24, and 5.6.8

### PR DESCRIPTION
**Pull request by GrahamCampbell**
### ~~DO NOT MERGE YET~~

~~These releases will only become available in the next 40-50 hours. I'm just getting this done in advance. :)~~

## Looks ready to me. :)

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
I think 5.5.24 we could already merge, don't you?

It is already released https://php.net/archive/2015.php#id2015-04-16-1

**Comment by GrahamCampbell** [comment]
> I think 5.5.24 we could already merge, don't you?

No.

**Comment by GrahamCampbell** [comment]
For example: http://php.net/distributions/php-5.4.40.tar.bz2. Not released yet.

**Comment by GrahamCampbell** [comment]
Just triggering travis so we can see the state of things.

**Comment by GrahamCampbell** [comment]
Also, do you think we should do a v0.11.0 release after this?

**Comment by GrahamCampbell** [comment]
Or maybe v1.0.0. What's holding us back?

**Comment by rogeriopradoj** [comment]
First, about new PHP versions:


I understand, @GrahamCampbell:

>I think 5.5.24 we could already merge, don't you?
> It is already released https://php.net/archive/2015.php#id2015-04-16-1

Maybe, we could go with separated PRs for each release in https://php.net/archive/2015.php.

**Comment by GrahamCampbell** [comment]
@rogeriopradoj I don't think that's really needed. PHP versions normally get released in the same 24 hour period, so splitting this up is probably overkill.

**Comment by rogeriopradoj** [comment]
About the versions of php-build itself:

@CHH, help us!

**Comment by rogeriopradoj** [comment]
About closing and opening PR in order to force rebuild, we have other option:

- going to https://travis-ci.org/php-build/php-build/pull_requests, open the build, and click and button **Restart build**.

See ya!

**Comment by GrahamCampbell** [comment]
Yeh, I'm just used to not having access to travis on this repo. :)

**Comment by GrahamCampbell** [comment]
Builds all seem to be working, though not all are done yet.

**Comment by CHH** [comment]
I'm all for going to v1.0.0, or we go down the same route as ruby-build and use date based version numbers, i.e. 20140416 and the like.

I think that we should think about things to clean up for 1.0, like the support for Pyrus (remember, it was introduced before composer was a thing).

**Comment by GrahamCampbell** [comment]
> I think that we should think about things to clean up for 1.0

I'll make a new issue so we can discuss the things that need doing before the 1.0 tag.

**Pull request merged**
