### PR TITLE
Rbenv features

### PR DESCRIPTION
**Pull request by madumlao**
This pull request backports some additional features from "upstream" rbenv/ruby-build into php-build. If it's too much in one go, I can split this up into separate PRs.

Everything here is already a feature in rbenv / ruby-build.

1) allows php-build to call hooks defined by phpenv and phpenv plugins. This allows phpenv plugin authors to perform additional actions on php-build. Needed for me to implement #460 in [phpenv-aliases][]

2) shows a prompt when phpenv install-ing a version that already exists. Adds appropriate `--force` / `--skip-existing` options for controlling behavior when version already exists. It's just a good idea.

3) adds command-line option for `--keep` that triggers `PHP_BUILD_KEEP_OBJECT_FILES` which prevents `make clean` from running.

4) removes `rbenv-*` executables from the repo. We don't use these, do we?

[phpenv-aliases]: https://github.com/madumlao/phpenv-aliases

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Awesome, thanks. :)

**Comment by mhart** [comment]
I think something is still trying to use the `rbenv-*` executables, see #516

**Comment by madumlao** [comment]
Noted in #516 - might require an update to CHH/phpenv rather than here.

**Comment by ikari7789** [comment]
CHH/phpenv is basically a dead project. It hasn't had any update since 2014, and I'm not sure that any maintainer is still around. It works by checking out rbenv and then basically just replacing any instance of .rb -> .php. Unfortunately, sometimes in updating, this can become broken, so keeping the rbenv-* versions of the files seems like a rather simple solution for now that won't break everyone's installations.

**Comment by madumlao** [comment]
@ikari7789 i responded on issue #516, lets try to keep the issue thread there. I agree one revert makes sense but other actions are needed too.

**Pull request merged**
