### PR TITLE
Fixed xdebug version

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @hnw.

**Comment by hnw** [comment]
Hmm... The new package name is `xdebug-2.4.0rc1.tgz`, however the directory name in the package is still `xdebug-2.4.0RC1`. Currently `share/php-build/extension/extension.sh` doesn't support such inconsistent package...

**Comment by GrahamCampbell** [comment]
:(

**Comment by GrahamCampbell** [comment]
Maybe just use xdebug master until 2.4.0 is relased?

**Comment by hnw** [comment]
I think it's better.

**Pull request merged**
