### PR TITLE
Added php 7.0.13 and 7.1.0 RC6

### PR DESCRIPTION
**Pull request by kunit**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
5.6.28 is now out as well.

**Comment by GrahamCampbell** [comment]
I normally just update this stuff myself once all 3 are released.

**Comment by GrahamCampbell** [comment]
Also, do all the other php 7.1 RCs still work? The core team have a habit of deleting them (which is why there's no earlier ones than RC3 or something).

**Comment by GrahamCampbell** [comment]
Will accept a further PR to add the other php update. Can't do it myself right now I'm afraid. Failing that, I'll just do it tomorrow. Thanks everyone. :)

**Pull request merged**
