### PR TITLE
Replace 7.2.0RC1 with 7.2.0RC2

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thank you. Please update the change log and the test script and travis.

**Comment by GrahamCampbell** [comment]
image

**Comment by hnw** [comment]
As I mentioned in #474, the following code in `.travis.yml` is a workaround. The issue in PHP 7.2.0RC1 is already fixed and now we can remove this code.

```
        if [[ "$DEFINITION" == "7.2.0RC1" ]]; then
            brew upgrade pkg-config
        fi
```

**Comment by hnw** [comment]
LGTM 👍

**Pull request merged**
