### PR TITLE
Rename unstable versions

### PR DESCRIPTION
**Pull request by henriquemoody**
Add a dash after the version name to perform a better sort on the versions' list.

See https://github.com/php-build/php-build/pull/302#issuecomment-128828066

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Does the dash actually make any difference?

**Comment by GrahamCampbell** [comment]
I'm not sure we should rename them.

**Comment by GrahamCampbell** [comment]
We need to just fix the order.

**Comment by GrahamCampbell** [comment]
So that 7.0.0 comes after 7.0.0beta.

**Comment by GrahamCampbell** [comment]
I really don't think we should rename them. I just made a typo in my comment on the other thread when i included dashes.

**Comment by henriquemoody** [comment]
you're right

**Pull request closed without merging**
