### PR TITLE
Remove potentially dangerous deletion

### LINKED ISSUE #125: Delete the destination folder on failed install
I just run the script with wrongly set path to $HOME (stupid), but imaging what this script did:

    function cleanup_abort {
        log "Warn" "Aborting build."

        rm -rf "$PREFIX"

        make -C "$TMP/source/$DEFINITION" clean &> /dev/null
    }

Just deleted all my HOME without any alert.

What I consider the bug here, that cleanup_abort, should only delete files it created!

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #125.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
// cc @php-build/owners This should probably have been addressed a while ago given that it could destroy somebody's box...

**Comment by rogeriopradoj** [comment]
LGTM.

**Comment by GrahamCampbell** [comment]
Going to merge this for now. We can always modify it again in the future if needed, though this fix is quite important.

**Comment by CHH** [comment]
👍🏻

**Pull request merged**
