### PR TITLE
Added latest PHP versions

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm.

> configure: WARNING: unrecognized options: --with-mcrypt
> configure: WARNING: This bison version is not supported for regeneration of the Zend/PHP parsers (found: 2.3, min: 204, excluded: ).
> configure: error: cURL version 7.10.5 or later is required to compile php with cURL support

**Comment by GrahamCampbell** [comment]
Ping @hnw.

**Comment by hnw** [comment]
The version of stock curl on xcode8 image seems to be 7.43.0, so the error message is inexplicable.

Building PHP 7.2.0RC1 with this Pull Request on my macbook is successful, which has macOS 10.11.6 + Xcode 8.1. 

It may be useless but please try to run test again.

**Comment by hnw** [comment]
I think this is PHP's bug. Building PHP 7.2.0RC1 + curl support always fail without pkg-config.

This issue might fix in PHP 7.2.0RC2.

As workaround, add `brew install pkg-config`.

**Comment by hnw** [comment]
I think this is a bug in the configure script. Building PHP 7.2.0RC1 + curl requires pkg-config and older pkg-config never scan stock libraries.

This issue might fix in PHP 7.2.0RC2.

As a workaround, we should upgrade pkg-config on Travis CI.

**Pull request merged**
