### PR TITLE
Added PHP 7.0.0 RC8

### PR DESCRIPTION
**Pull request by GrahamCampbell**
We'll get there in the end. ;P

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. Build failed.

**Comment by GrahamCampbell** [comment]
Ping @php-build/owners.

**Comment by henriquemoody** [comment]
Do you have any clue of what happens?

**Comment by hnw** [comment]
Downloading Xdebug is failed because the package has been changed; `xdebug-2.4.0RC1.tgz` => `xdebug-2.4.0rc1.tgz` (It should be by mistake....).

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Pull request merged**
