### PR TITLE
Add PHP versions

### PR DESCRIPTION
**Pull request by henriquemoody**
- [5.4.44](https://github.com/php/php-src/releases/tag/php-5.4.44)
- [5.5.28](https://github.com/php/php-src/releases/tag/php-5.5.28)
- [5.6.12](https://github.com/php/php-src/releases/tag/php-5.5.12)
- [7.0.0beta3](https://github.com/php/php-src/releases/tag/php-7.0.0beta3)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by GrahamCampbell** [comment]
You forgot to update the test config.

**Comment by GrahamCampbell** [comment]
See https://github.com/php-build/php-build/pull/294.

**Comment by henriquemoody** [comment]
Ready to merge.

**Comment by GrahamCampbell** [comment]
Thanks.

**Pull request merged**
