### PR TITLE
Support php-7.0.4

### PR DESCRIPTION
**Pull request by hirak**
PHP-7.0.4 released.
http://php.net/index.php#id2016-03-03-1

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
we'll do this once 5.6 is ready too

**Comment by GrahamCampbell** [comment]
thanks though

**Comment by mlocher** [comment]
@GrahamCampbell [5.6 is ready now](http://php.net/archive/2016.php#id2016-03-03-3), should I submit a PR or is there already a prepare one?

**Comment by GrahamCampbell** [comment]
I normally just do this myself to ensure both test files and the changelog don't get forgotten about.

**Comment by mlocher** [comment]
sounds good, thanks :+1:

**Pull request closed without merging**
