### PR TITLE
Added 7.3.29, 7.4.21, 8.0.8

### PR DESCRIPTION
**Pull request by dktapps**
This was done using a script I've been working on recently. It's not able to automatically update the changelog, but everything else can be done automatically. If desired, I can provide it, so that you can use it in an automated GitHub Actions cron job.

### CODE REVIEW

**Comment by dounokouno** [comment]
@dktapps 

I fixed the CI fail and sent the PR. Please confirm it.

https://github.com/dktapps/php-build/pull/1

**Comment by dounokouno** [comment]
I forked the main repository from this PR branch and sent a PR that fixes the GitHib Actions CI fail.

PR #672

Tahnk you.

**Comment by dktapps** [comment]
Hello, any maintainer alive out here?

**Comment by dounokouno** [comment]
The following PR has merged the additions of PHP 7.3.29, 7.4.21 and 8.0.8.

PR #672

The above PR has been forked from this PR. Thank you very much.

**Pull request closed without merging**
