### PR TITLE
Add 8.3.0

### PR DESCRIPTION
**Pull request by Xerkus**
PHP 8.3.0 just released.

This adds definitions for 8.3.0 and updates snapshot to follow 8.3 branch

### CODE REVIEW

**Comment by Xerkus** [comment]
Same xdebug change would need to be applied to 8.2 snapshot as well since I took it from there?

**Comment by Xerkus** [comment]
xdebug compiles from master but not from alpha3. Is xdebug a blocker for stable 8.3.0 here?

errors building alpha3 make no sense to me
```
/tmp/php-build/source/xdebug-3.3.0alpha3/php_xdebug.h:21:1: error: version control conflict marker in file
   21 | <<<<<<< Updated upstream
      | ^~~~~~~
```
This looks like build script fails to checkout a tag cleanly since conflict markers are not in that tag but they are there when I inspect tmp folder. There are committed conflict markers in xdebug.ini file however which were removed in master branch.

```
/tmp/php-build/source/xdebug-3.3.0alpha3/src/lib/llist.h:40:34: error: unknown type name 'xdebug_llist_dtor';
```
this one is defined in same file only several lines above. :shrug: Error does not appear when building from master branch with no related changes there that I can see. Probably another checkout issue

**Comment by Xerkus** [comment]
sorry. I am in over my head here. 

@GrahamCampbell your issue matches the error exactly https://github.com/php/php-src/issues/11603 but I do not know how to apply it here.

**Comment by GrahamCampbell** [comment]
It's not the same issue, but it is similar. We should report it to PHP. Do you mind to do that, please?

**Comment by Xerkus** [comment]
I don't really understand what it actually means. I would prefer if you do it.

**Comment by Xerkus** [comment]
Can newer binutils (from epel?) be installed on centos here?

**Comment by mzch** [comment]
Is it possible to add new `8.1.26` and `8.2.13`?

**Comment by Xerkus** [comment]
@GrahamCampbell there won't be a fix other than what we can do here. What is the way forward?
 I see two options: install epel and newer binutils or exclude centos from build for 8.3

**Comment by viceice** [comment]
Any chances to get this merged soon?

**Comment by RolphH** [comment]
@GrahamCampbell any updates on this?

**Comment by RolphH** [comment]
@rogeriopradoj @loicfrering @CHH can you help out here. Not having support for 8.3.0 is blocking other projects :(

**Comment by RolphH** [comment]
As Centos 8 is EOL since December 31, 2021, can't we remove CentOS 8? Or replace with RockyLinux, see also #707

**Comment by Xerkus** [comment]
My laptop failed. I can't run this locally.

From build log it does not appear that binutils were installed or updated. Running yum/dnf update can potentially fix this failure, according to the replies in the issue linked above.

Also rebased.

**Comment by GrahamCampbell** [comment]
Build still fails.

**Comment by bobvandevijver** [comment]
Looks like the `binutils` update didn't have anything to do: https://github.com/php-build/php-build/actions/runs/7210237335/job/19643180849?pr=759#step:4:772.

**Comment by Xerkus** [comment]
Latest available binutils is 2.30 and 2.31 contains the fix. https://linux-packages.com/rocky-linux-8/package/binutilsx86-64
Is it available from some other package?

What is gcc-toolset-10-binutils?

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Please rebase, exclude builds for centos7 and rockylinux8, and revert the binutils change. I anticipate this will build correctly on rockylinux9.

**Comment by viceice** [comment]
@GrahamCampbell please approve CI checks

**Review by GrahamCampbell — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Thanks for sticking with this.

**Pull request merged**
