### PR TITLE
Fixed macOS CI for PHP 5.x

### PR DESCRIPTION
**Pull request by kunit**
https://github.com/php-build/php-build/issues/596

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Can we install 1.1 on php 7?

**Comment by kunit** [comment]
The current openssl package is 1.1, so we can install 1.1 using "openssl" instead of "openssl@1.1".

refs: https://github.com/Homebrew/homebrew-core/pull/47034

**Comment by GrahamCampbell** [comment]
Oh, ok.

**Comment by GrahamCampbell** [comment]
This looks great, thanks. I'll just wait for Travis to finish up to be sure, though based on the earlier runs within this PR, I expect it to all pass. :)

**Pull request merged**
