### PR TITLE
Add 8.0snapshot definition

### PR DESCRIPTION
**Pull request by nick-zh**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for getting started on this. Please can you name this new version `8.0snapshot`. I will adjust the branch from master to `PHP-8.0` once the PHP core team branch off, which should be in the next few weeks.

**Comment by nick-zh** [comment]
@GrahamCampbell yes, sure thing :v:

**Comment by GrahamCampbell** [comment]
The following warnings also need to be fixed:

```
WARNING: unrecognized options: --with-png-dir, --with-libxml-dir, --with-icu-dir
```

**Comment by nick-zh** [comment]
@GrahamCampbell yeah i saw, but i am not sure where they are coming from :smile: somehow didn't see them in the default configure options, but i must be missing something

**Comment by GrahamCampbell** [comment]
It seems to be caused by line 673 of php-build. I suppose this bug is unrelated to this PR, then. Since PHP 7.4.9 on macos will also be generating this warning.

**Comment by nick-zh** [comment]
@GrahamCampbell ah yeah i see, inside the build there are a few osx ifs which add those, if you want i can create a separate PR for this where this is ommited for 7.4 up

**Comment by GrahamCampbell** [comment]
> if you want i can create a separate PR for this where this is ommited for 7.4 up

That's be perfect. 🍻

**Comment by nick-zh** [comment]
@GrahamCampbell not too sure how to fix the latest build error. When searching for the error there are several solution attempts for this, but i am not too versed with OSX. Maybe you have had this before. If not i will try create my own travis setup with darwin, since i can't run the job in debug mode to figure this out :smile:

**Comment by nick-zh** [comment]
@GrahamCampbell build has a lot of keyserver timeouts, maybe you can restart them after, but the build should now be ok :v:

**Comment by GrahamCampbell** [comment]
Thanks. :+1:

**Pull request merged**
