### PR TITLE
Added php 7.0.0beta1

### PR DESCRIPTION
**Pull request by tamcap**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We always add all new php releases together. I'll be doing this later today once they're all available.

**Comment by tamcap** [comment]
Oops, sorry, I was simply following the convention from https://github.com/php-build/php-build/commit/174bbb34c09c4bbf7fe558a84542b001d459ea1d

**Comment by GrahamCampbell** [comment]
Ahh, but that release was out of cycle. :)

**Comment by rogeriopradoj** [comment]
Hi, @GrahamCampbell , I think we could revert this cycle for what it was originally, I mean, accepting sole releases as long as they are available in:

- http://php.net/ upper right menu, for new 'stable' releases (nowadays 5.4.x, 5.5.x and 5.6.x)
- http://php.net/ main content, for new 'development/next' releases (nowadays 7.x)

This way, we could have `php-build` updated more frequently.

@php-build/collaborators @php-build/owners what do you say?

**Comment by GrahamCampbell** [comment]
@rogeriopradoj All the releases came out within the same day, so I don't see the point in changing this.

**Comment by GrahamCampbell** [comment]
> This way, we could have php-build updated more frequently.

It was still updated within hours.

**Comment by rogeriopradoj** [comment]
Perfect!

**Pull request closed without merging**
