### PR TITLE
Add 8.1.30, 8.2.24, 8.2.25, 8.3.12 & 8.3.13

### PR DESCRIPTION
**Pull request by mzch**
Add 8.1.30, 8.2.24, 8.2.25, 8.3.12 and 8.3.13.

### CODE REVIEW

**Comment by keyhelp** [comment]
Thank you mzch.
It is a pity that the new versions are no longer merged as quickly as they were a few months ago.

**Comment by komapa** [comment]
Can this be merged please?

**Comment by dounokouno** [comment]
@GrahamCampbell Could you please confirm?

**Comment by dounokouno** [comment]
Thanks 🙌

**Pull request merged**
