### PR TITLE
Added PHP 7.1.0beta2

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Is this going to be merged? We are in a chicken-and-egg situation here, if you are waiting for Travis to pass these builds; Travis needs them merged before we can package 7.1.0 beta2.

**Comment by GrahamCampbell** [comment]
PHP hadn't actually released this yet so we can't merge this. The download link was 404ing.

**Comment by GrahamCampbell** [comment]
PHP aren't releasing this until 8th August apparently.

**Comment by GrahamCampbell** [comment]
> if you are waiting for Travis to pass these builds

The build will pass once the PHP team actually upload the archive for us to build it. :)

**Comment by BanzaiMan** [comment]
Ah! OK. We will wait patiently.

**Comment by GrahamCampbell** [comment]
Seems PHP have now released this, but backdated their blog post!

**Comment by GrahamCampbell** [comment]
Retriggering the build now. If it passes, I'll merge. :)

**Pull request merged**
