### PR TITLE
PHP 7.0.7

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thank you very much, but I normally update all the PHP versions at the same time. I've got it done on my machine already, ready to push once they'll all ready on php.net.

**Comment by Ocramius** [comment]
@GrahamCampbell can you add these rules to `CONTRIBUTING.md` eventually? I was really hoping to get travis-ci running 7.0.7 tomorrow, but this kinda killed my plans :|

**Comment by GrahamCampbell** [comment]
PHP 7.0.7 support is now available on the master branch.

**Comment by GrahamCampbell** [comment]
@Ocramius I normally make a PR a few days before the PHP team actually tag the releases to be clear to everyone I've not forgotten, so PRs like this don't crop up. I've been a bit overloaded recently, so didn't bother making the PR. Sorry for any confusion.

**Comment by Ocramius** [comment]
Alright

**Comment by tiger-seo** [comment]
thank you, guys :wink:

**Pull request closed without merging**
