### PR TITLE
Update `download_from_github` function

### PR DESCRIPTION
**Pull request by henriquemoody**
Clones the repository and its submodules instead of download the tarball from GitHub.

***
I was starting to work on HHVM implementation, but it's necessary to update the `configure_package` function with a lot of things and I don't think I'm gonna have time to do it now.
I decided to send this pull request because maybe it can be useful for another person.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
How does this compare performance wise. How much slower is it?

**Comment by henriquemoody** [comment]
Actually I didn't measure it but because of `--depth=1` it's much faster than a normal clone.

PS.: The only problem on the current approach and the reason for this change is because the GitHub's tarball doesn't include the submodules
PSS.: There are no submodules on [PHP](https://github.com/php/php-src) repository, but on [HHVM](https://github.com/facebook/hhvm) they are necessary to compile.

**Comment by henriquemoody** [comment]
I made a quick test using `time`:

```bash
time download_from_github "$branch" "$repo"
exit 3
```

**On `master`**

Test 1
```
real    0m43.117s
user    0m1.183s
sys 0m3.438s
```

Test 2
```
real    0m25.682s
user    0m1.299s
sys 0m4.093s
```

**On my branch**

Test 1
```
real    0m29.384s
user    0m3.031s
sys 0m5.087s
```

Test 2
```
real    0m27.225s
user    0m2.922s
sys 0m4.943s
```

**Comment by GrahamCampbell** [comment]
Ok, looks pretty good to me. Ping @php-build/owners.

**Comment by GrahamCampbell** [comment]
Ping @rogeriopradoj.

**Comment by henriquemoody** [comment]
How about you guys use [Lazy consensus](https://rave.apache.org/docs/governance/lazyConsensus.html)?

**Comment by rogeriopradoj** [comment]
> How about you guys use Lazy consensus?

@henriquemoody , that is a interesting option, but I think we, new guys in the project, have some need of the approval from @CHH.

Thats why big changes in the project take a little longer, right?

---

Anyway, I think the function that you created is awesome, perhaps I would prefer if it would be called `clone_from_github` or something similar to it. And keep the `download_from_github` as it is.

I know that @humanshell versions of php-build and phpenv have chosen to use cloning: https://github.com/phpenv/phpenv/issues/1#issuecomment-6080798.

I think would be great for https://github.com/php-build/php-build if you have all these options, and let the users pick what is best for each one.

---

So, about the content code: :+1:  (just changing the name of function and keeping the original download_from_github).

---

Ping others @php-build/owners to discuss on this!

See ya!

**Comment by CHH** [comment]
:+1: but, I also think it would be better as a separate function.

@php-build/owners OT, but lazy consensus looks good to me, especially since I don't have much time to commit to the project these days. I think not everything has to run by me anymore.

**Comment by rogeriopradoj** [comment]
Thanks, @CHH !

> :+1: but, I also think it would be better as a separate function.

@henriquemoody, can you work on that?

@php-build/owners for applying lazy consensus maybe we show invite some more to be part of the team (maybe not owners for now, but with high privileges at least for helping with the discussion and merging if necessary), what do you say?

I suggest to invite the guys that are close to the project these times: @gerardroche and @henriquemoody.

**Comment by CHH** [comment]
@rogeriopradoj good idea, could you take care of adding them?

**Comment by rogeriopradoj** [comment]
@CHH done!

**Comment by CHH** [comment]
@rogeriopradoj thanks!

**Comment by henriquemoody** [comment]
Hey, guys.

I was in vacation these days, that's the reason of my late.

> Anyway, I think the function that you created is awesome, perhaps I would prefer if it would be called `clone_from_github` or something similar to it. And keep the `download_from_github` as it is.

That comes to my mind I just did want to break API, but since you guys think it's better I will rename that.

> :+1: but, I also think it would be better as a separate function.

Checked.

> I suggest to invite the guys that are close to the project these times: `@gerardroche` and `@henriquemoody`.

Thanks guys, I really didn't expect that, but I will do the best I can!

**Comment by rogeriopradoj** [comment]
:smile: Welcome aboard @henriquemoody and @gerardroche

**Comment by gerardroche** [comment]
:+1:

**Pull request closed without merging**
