### PR TITLE
Update gh-pages as #271

### PR DESCRIPTION
**Pull request by rogeriopradoj**

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
@php-build/owners in fact I think we could create a repo php-build.github.io and move this gh-pages branch there. What do you guys think?

**Comment by CHH** [comment]
good idea, go for it.

--
Ing. Christoph Hochstrasser

📧 christoph@hochstrasser.io
📱 +43 664 922 86 51
🌍 www.hochstrasser.io

🏢
Kapuzinergasse 6
A-3340 Waidhofen an der Ybbs
—
UID: ATU68701078
—
Bankverbindung:
Sparkasse Niederösterreich • BIC: SPSPAT21XXX • IBAN: AT55 2025 6000 0095 6227

**Comment by GrahamCampbell** [comment]
:+1: for a separate gh pages repo.

**Comment by rogeriopradoj** [comment]
Created repo, and moved pull request to php-build/php-build.github.io#1

**Pull request closed without merging**
