### PR TITLE
Add PHP versions

### PR DESCRIPTION
**Pull request by henriquemoody**
- 5.4.45
- 5.5.29
- 5.6.13
- 7.0.0RC2

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you add the 7.0.0 RC2 release too please?

**Comment by henriquemoody** [comment]
Yes, but it's was not released yet. 

Looks like they haven't created the package for 5.4.45 as well.

BTW, I didn't add `php-5.6.13RC1` to the list, do you think I should do it?

**Comment by GrahamCampbell** [comment]
> BTW, I didn't add php-5.6.13RC1 to the list, do you think I should do it?

No.

**Comment by GrahamCampbell** [comment]
> Yes, but it's was not released yet.

Yes, but neither has 5.4.45. We always add the hole set of releases together. Please include eveything.

**Comment by henriquemoody** [comment]
Good to merge.

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Pull request merged**
