### PR TITLE
add master definition

### PR DESCRIPTION
**Pull request by nick-zh**
I think this makes sense for future master / nightly builds, since the current 8.0 snapshot will move to the 8.x branch anyway soon
As per the discussion here: https://github.com/travis-ci/php-src-builder/pull/53

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but I have no plans to support this.

**Comment by GrahamCampbell** [comment]
When master becomes 8.1, I will create a 8.1snapshot and adjust the 8.0snapshot build.

**Comment by nick-zh** [comment]
@GrahamCampbell i assume 8.1snapshot will use the master branch, i am not sure how this is different to having a master definition. Maybe you can explain the goald behind it. Sry i am new to php-build actually, just trying to get the nightly image back on travis (to test an extension against php8) and saw they build it using php-build :smile:

**Comment by GrahamCampbell** [comment]
I don't think a master build is ever useful. It is only useful to have major.minor version snapshot builds. There is also of course the possibility that there won't be a "master" branch in PHP forever.

**Comment by nikic** [comment]
FWIW I do think having master is pretty useful, especially for extensions that want to test whether they build on current PHP master.

The actual PHP version that master points to is irrelevant if you just want to test the bleeding edge, whatever it may be.

**Comment by nick-zh** [comment]
@GrahamCampbell is the decision to not bring master back final? If so, i can re-ping in the travis pr, i am eager to have a nightly image back for my build :v:

**Comment by derickr** [comment]
Xdebug author here!

> I don't think a master build is ever useful.

Yet, that is exactly what I do want to do. I would like the absolute latest version so I can test when PHP's master branch break APIs, and as soon as that happens so I can fix my extension. I don't care what it is called though, but it shouldn't be something that I need to update at all. (ie, no 8.0snapshot to 8.1snapshot changes).

**Comment by BanzaiMan** [comment]
The name `master`, corresponding to the [`master` branch](https://github.com/php/php-src/tree/master), seems like a useful build target. Sure, the name `master` may change, but there will always be a name that indicates "bleeding edge" in the PHP development; if it changes, then the name here should also change.

**Comment by morrisonlevi** [comment]
Extension author here. I also want to test out PHP's master branch. Of course things may break and it may have nothing to do with my extension, but such is the nature of bleeding edge work.

**Comment by DanielBadura** [comment]
Which harm do we cause if the get the master build target as an nightly-build? Is this a huge maintain burden?

**Comment by smola** [comment]
The problem of naming `master` as `8.1snapshot`, other than needing periodical updates, is that as soon as `master` moves version, `phpenv` will install the incorrect version unless it is updated. So a stale checkout would lead to misleading behavior.

**Comment by nick-zh** [comment]
Another good point, thank you @smola. I think the participation, discussion and input here has shown, that having master is indeed valuable, especially for extension developers. I really hope we can get the PR reopened and merged.

**Comment by derickr** [comment]
Why has this not been reopened? "master" is something extension authors clearly want.

**Comment by krakjoe** [comment]
If we ain't got master, we got no _continuous_ integration as extension developers ... please reconsider ...

The alternative is that extension developers will roll their own build of php-master, on your infrastructure, wasting many resources, killing many polar bears and trees (non-polar) ... and so on ...

Why do you want to kill polar bears !?

**Comment by GrahamCampbell** [comment]
Both having a master and not having a master require you to update your config, and using master is worse IMO. If you are using master, then once master becomes 8.1, you are no longer testing against 8.0, which is soon to be stable, and you might not notice for months! Very bad. Better to opt in to next release rather than to accidentality stop testing against the version everyone is about to upgrade to!

I will provide `8.1snapshot` soon. Call it master if you want (in your head), it doesn't matter. It's just a name.

**Comment by derickr** [comment]
It *does* matter, because then we need to change our config anything you feel like changing a name. By having a "master" name, no changes have every to be made on our side to continue testing against the latest development branch. 

Nobody on this thread seems to agree with your stance, so perhaps it's wise to change it?

**Comment by GrahamCampbell** [comment]
You have to change the config every year anyway?

**Comment by GrahamCampbell** [comment]
@smola also raises a valid concern.

**Comment by nick-zh** [comment]
So trying to sum up the input, that was gathered here:
- i think we are agreeing, that having snapshots can cause problems on an outdated state [as pointed out](https://github.com/php-build/php-build/pull/638#issuecomment-687151321) by @smola
- having no master, is tedious for ext developers, we want to be on bleeding edge to ensure future compatibility (would mean snapshot hopping without master)

I understand there is a transition phase where non-ext developers will want to test their packages etc. as well.
But both concepts `master` and `snapshot` are still volatile, since they are based on master.
Personally i think everybody using master in open project, should be aware, that stuff might fail (hence not released).
From the gathered points, i think having a master has more advantages in the end.
I hope i forgot nothing.

**Pull request closed without merging**
