### PR TITLE
Remove pear and pyrus

### LINKED ISSUE #344: pear.php.net certificate issue prevents compilation (no recent nightly builds on Travis CI)
PHP nightly builds have been failing the last 2 days. First, via connection timeout to pear.php.net, then now with certificate issue with the same host.

https://travis-ci.org/travis-ci/php-src-builder/jobs/94094279#L241-L247

```
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
--2015-12-01 05:04:39--  https://pear.php.net/install-pear-nozlib.phar
Resolving pear.php.net (pear.php.net)... 5.35.241.22
Connecting to pear.php.net (pear.php.net)|5.35.241.22|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `pear.php.net'.
To connect to pear.php.net insecurely, use `--no-check-certificate'.
```

Besides some custom configuration, the basic command we run is:

```
php-build -i development "${VERSION}" "${INSTALL_DEST}/${VERSION}"
```

(https://github.com/travis-ci/php-src-builder/blob/b51704810069121730270bdd9f79b5617d6fb7f8/bin/compile#L19)

### PR DESCRIPTION
**Pull request by GrahamCampbell**
// cc @php-build/owners

---

Closes #344.

### CODE REVIEW

**Comment by CHH** [comment]
Looks good and it’s the right thing to do. Maybe we could bring PEAR back for people who need it later on with an event system for plugins to hook into.

**Comment by GrahamCampbell** [comment]
> We could also start to encourage Pickle as replacement for pecl.

Indeed.

**Comment by GrahamCampbell** [comment]
> Maybe we could bring PEAR back for people who need it later on with an event system for plugins to hook into.

TBH, I don't think we even need to. Surely they can just use an older version of phpbuild?

**Comment by stof** [comment]
It may have been great to discuss this with the Travis team first. This kind of broke the support of PHP images on Travis for anyone relying on pecl

**Comment by GrahamCampbell** [comment]
> It may have been great to discuss this with the Travis team first. This kind of broke the support of PHP images on Travis for anyone relying on pecl

They can choose not to update their version of php-build for now if they want.

**Comment by GrahamCampbell** [comment]
> Maybe we could bring PEAR back for people who need it later on with an event system for plugins to hook into.

Travis can send us a PR with this if they really want pear support.

**Comment by stof** [comment]
@GrahamCampbell well, the PR would be a matter of running ``git revert`` on this merge, right ?

**Comment by stof** [comment]
> They can choose not to update their version of php-build for now if they want.

Given that there is no tagged release before the removal and that the previous release is from 2013, it is kind of hard to install the right version of phpbuild (as they need all the fixes they contributed in the meantime)

**Comment by GrahamCampbell** [comment]
> well, the PR would be a matter of running git revert on this merge, right ?

No. That would not be accepted. The PR would be to add a hook system.

**Comment by beanieboi** [comment]
hey,

ben from Codeship here. We use php-build in the same way Travis CI does. We have no other choice than preinstall and support really old versions and people's old PHP apps. Sadly the PHP community is not a fast moving community and we still have a lot of people using PEAR etc.

I'm not really involved in the PHP ecosystem. Do you have suggestion on what we can do to support old PHP versions with PEAR. I really want to avoid forking php-build and maintain a version without this change.

thanks a lot for php-build. i would love to help, but i need some advice where to put my time!

thanks
ben

**Comment by GrahamCampbell** [comment]
@beanieboi If you're able to PR that extension system we need, that would be great.

**Comment by rogeriopradoj** [comment]
Hi, @beanieboi and @stof , what's up? Thanks for getting involved on this.

We know that removal of PEAR made a little mess with https://github.com/travis-ci, but fortunatelly @BanzaiMan and others contributors worked very well to remedy this.

On https://github.com/travis-ci/travis-ci/search?q=pear&type=Issues&utf8=%E2%9C%93 we can find more information about the work they did (mainly in https://github.com/travis-ci/travis-ci/issues/5256).

@stof @beanieboi @BanzaiMan do you guys we could work together in order to create this extension/hook for php-build?

**Comment by rogeriopradoj** [comment]
Oh, in time, about the pecl extension installing replacement, our friends from Travis-CI are working on at https://github.com/travis-ci/travis-ci/issues/5266.

**Comment by beanieboi** [comment]
thanks for the heads up! i'll read through all of this now! :)

**Comment by stof** [comment]
@rogeriopradoj I'm not working on it. I don't have time for that (I already don't have enough time for all the projects where I'm maintainer these days). Thus, I'm not a direct user of php-build (I went in this discussion because I'm one of the reporter of the issues on Travis-CI related to the removal).
And I don't know php-build enough either to be able to propose an architecture for a hook system (I have very few idea about how it works)

**Pull request merged**
