### PR TITLE
Fixing Snapshot Versions

### PR DESCRIPTION
**Pull request by dasrecht**
Hi There

I removed the snapshot definitions since snaps.php.net has gone away.

I could not find another solution to snaps.php.net unfortunately.

/bastian

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Hi, @dasrecht , thanks for the PR.

According to https://bugs.php.net/bug.php?id=67804:

>[2015-02-18 21:07 UTC] jacob@php.net
>Hi,
>http://snaps.php.net has be decomissioned in favour of the git snapshots
>available at https://github.com/php/php-src. 

Instead of removing, what do you think to update the urls for the ones available on GitHub?

We could use the function `install_package_from_github` https://github.com/CHH/php-build/blob/master/bin/php-build#L473 that is already available.

Example of a definition in repo that is using already the `install_package_from_github`: https://github.com/CHH/php-build/blob/master/share/php-build/definitions/master#L1

Probably it would be something like this:

```
install_package_from_github PHP-5.4
install_pyrus
install_xdebug "2.3.2"
```

Can rebase your PR, or send a new one? Let us know if you need some help with it, ok?

Thanks!

**Comment by rogeriopradoj** [comment]
Oh @dasrecht , perhaps it can help, the branches in https://github.com/php/php-src/branches:

- PHP-5.6
- PHP-5.5
- PHP-5.4

**Comment by dasrecht** [comment]
Hi there. Yes taking on the branches of php-src sounds like a splendid idea! I'll reroll my PR to make that happen.

**Comment by rogeriopradoj** [comment]
Ok! Let us know when it's ready for reviewing. 

See ya!

**Comment by GrahamCampbell** [comment]
Ping @dasrecht. This is a blocker for our v1.0.0 release.

**Comment by dasrecht** [comment]
uh, sorry for that. i'm on that right away!

**Comment by dasrecht** [comment]
fixed :)

**Comment by rogeriopradoj** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Could you squash to one commit please, then :+1: from me. Alternatively, we can squash it manually on merge.

**Comment by dasrecht** [comment]
Hi Graham, can you squash it at merge please? I think it's easier than redoing the whole PR.

Thanks!

**Comment by CHH** [comment]
👍🏻

**Comment by GrahamCampbell** [comment]
Merged. Thank you. :)

**Pull request closed without merging**
