### PR TITLE
Add PHP 7.1.19 and 7.2.7

### PR DESCRIPTION
**Pull request by hnw**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Could you also add 7.1.19, and then we'll merge.

**Comment by hnw** [comment]
It seems there's no new version for 7.1.x. See http://www.php.net/ .

**Comment by GrahamCampbell** [comment]
There will be, they've just not put it on their website yet. This is why I've not updated the php 7.2.x yet, since we do them both at once.

**Comment by GrahamCampbell** [comment]
Great, thanks.

**Pull request merged**
