### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by gerardroche**
These scriptlets don't need to be executable

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
They're fine being executable. I don't see why we should change the file permissions on those?

**Comment by GrahamCampbell** [comment]
Leave this open for the rest of the team to review I guess. :)

**Comment by gerardroche** [comment]
It's always a good thing to limit permissions on files.

**Comment by GrahamCampbell** [comment]
Ping @CHH.

**Comment by rogeriopradoj** [comment]
If it's not necessary to have the permissions "elevated", I vote for accept the pull request.

@GrahamCampbell, I think @CHH was not so close in the time of inclusion of these scripts (the most recent, I mean). Maybe @loicfrering could say better what he thinks about it.

**Comment by rogeriopradoj** [comment]
Thanks, @gerardroche !

**Pull request merged**
