### PR TITLE
install_package url change from https://git.php.net/ to https://museum.php.net/php5/

### PR DESCRIPTION
**Pull request by kunit**
We're going to discontinue the git.php.net server, so switch to museum.php.net.

https://externals.io/message/113838

### CODE REVIEW

**Comment by jrfnl** [comment]
Just checking - is `http` the correct protocol or should this be `https` for museum.php.net ?

**Comment by kunit** [comment]
It was `http` that was written in https://www.php.net/releases/, but it seems that https is also good, so I will change it to `https`.

**Comment by GrahamCampbell** [comment]
I think every PHP 5.x release can be found on there? Can you update all the files please?

**Comment by GrahamCampbell** [comment]
Oh, I see the rest come from secure.php.net. No problem then. :)

**Comment by GrahamCampbell** [comment]
Thanks a lot for this. 🍻

**Pull request merged**
