### PR TITLE
Revert 9286b152e78da7174631e78c1c3fdf0ffcf84c96

### PR DESCRIPTION
**Pull request by rogeriopradoj**
Reverts php-build/php-build#321 as pointed in https://github.com/php-build/php-build/pull/321#issuecomment-154826812

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: All tagged definitions we have always use xdebug tags.

**Comment by GrahamCampbell** [comment]
I'm, :-1: for even including debug on these releases anyway, since xdebug is only claiming to be compatible with php 7.0.0, not the RC releases.

**Comment by GrahamCampbell** [comment]
Ping @php-build/owners. We have an undecided situation here. ;P

**Comment by rogeriopradoj** [comment]
;-) @php-build/collaborators

**Comment by CHH** [comment]
The way I understand this is that changing to using tagged XDebug releases is done to get more predictable build results, right? If that's the case, then this is in my opinion a good thing. But I haven't any idea how PHP 7 and XDebug currently play together. If XDebug doesn't work with PHP 7, then I think it would be acceptable to leave it out for these definitions.

> I think we will have to get back to the origins of contributing with one repository where more than one person is responsible for code review and not merging our own changes/PRs at all. Make the discussion happen in PRs and Issues in order to see what other members think about the changes. Even if the project has to wait a few more minutes/hours/days to get updated. This way we could make this kind of arguing a little less infrequent, right?

I think this sounds like the right thing to do and I've seen that on quite a couple other projects as well. I think people trust us and doing reviews on changes is definitely good. I'm not sure if it's necessary on new definitions, but then I think a consistent policy of reviewing every PR is better than doing that inconsistently on only some PRs.

Let me tell you that you all are doing a great job @php-build/owners!

(Did that come out alright? It's late in the evening here)

**Comment by GrahamCampbell** [comment]
Sure, but in this case, I'm not sure it even matters that much, since these definitions will be getting removed in a few weeks anyway once we have a few stable php 7.0 definitions in here.

**Comment by GrahamCampbell** [comment]
I think we should definitely use the beta2 tag in the actual stable php 7 definitions though, when both are released. Do we all agree on that part at least?

**Comment by henriquemoody** [comment]
I agree with @GrahamCampbell on that.

**Comment by rogeriopradoj** [comment]
> Let me tell you that you all are doing a great job @php-build/owners!

Thanks, @CHH . I think mainly after @GrahamCampbell, and more recently @henriquemoody, came aboard the project got much better! These guys are really amazing.

And after that we got more contributions as well, improving a lot the codebase that was already much important for so many users!

**Comment by rogeriopradoj** [comment]
Now on the thoughts:

> I think we should definitely use the beta2 tag in the actual stable php 7 definitions though, when both are released. Do we all agree on that part at least?

I agree: when stable get published we should use the supported xdebug version linked with its official website. If at the time it is beta2, go with that!

--

> since these definitions will be getting removed in a few weeks anyway once we have a few stable php 7.0 definitions in here.

Sadly, more weeks... http://news.php.net/php.internals/89100

--

So, my point, still: for these pre-release definitions, we should go with **xdebug_master**.

Let's vote?

For php 7 stable definition (when it get published on PHP.net):
-------------------------------------------------------------------------------

| Member | Vote |
| ----------------- | ------------- |
| @rogeriopradoj  | install_xdebug "2.4.0beta1" |
| @GrahamCampbell   | install_xdebug "2.4.0beta1"  |
| @CHH | install_xdebug "2.4.0beta1" |
| @henriquemoody | install_xdebug "2.4.0beta1" |
| @loicfrering | - |

For every pre-release definitions (including RCs, alphas and betas, besides definition **master**):
----------------------------------

| Member | Vote |
| ----------------- | ------------- |
| @rogeriopradoj  | always use install_xdebug_master when it's available for that PHP version  |
| @GrahamCampbell   | always pick the current tagged release, now install_xdebug "2.4.0beta1"  |
| @CHH | - |
| @henriquemoody | - |
| @loicfrering | -  |

Do you think the votes are ok?

**Comment by GrahamCampbell** [comment]
https://github.com/php-build/php-build/commit/d176b8d16e7d911d5b665fed1998aef7d6fb481a#commitcomment-14371817

**Comment by GrahamCampbell** [comment]
https://github.com/php-build/php-build/commit/d176b8d16e7d911d5b665fed1998aef7d6fb481a#commitcomment-14371817

Looks like master doesn't even work anyway.

**Comment by CHH** [comment]
My vote on the "For every pre-release definitions" question:

I would use the latest working version of XDebug, preferring tagged stable versions, then tagged prereleases, and then falling back to master, if nothing else works.

**Comment by CHH** [comment]
Also, we could eventually think about disabling XDebug by default and moving it to a plugin. Since phpdbg was added to core since 5.6, things like collection of code coverage work without XDebug.

**Comment by rogeriopradoj** [comment]
Alright, guys, closing this PR. Votes are pretty clear ;-)

**Comment by rogeriopradoj** [comment]
xdebug-master is back in https://github.com/php-build/php-build/pull/338

**Comment by GrahamCampbell** [comment]
Yeh. Turned out we couldn't use the RC versions because our code to load them didn't work.

**Pull request closed without merging**
