### PR TITLE
Add patch mode for configure

### PR DESCRIPTION
**Pull request by mizunashi-mana**
Because current PHP archive includes `configure`:

```
$ tar tf /var/tmp/php-build/packages/php-7.2.9.tar.bz2 | grep configure
php-7.2.9/configure
php-7.2.9/Zend/configure.ac
php-7.2.9/configure.ac
php-7.2.9/TSRM/configure.ac
php-7.2.9/win32/build/configure.bat
php-7.2.9/win32/build/configure.tail
php-7.2.9/ext/mbstring/libmbfl/configure.ac
php-7.2.9/ext/bcmath/libbcmath/configure
php-7.2.9/ext/bcmath/libbcmath/configure.ac
```

, we should restore source and run `buildconf` to apply patches.

And, I improved outputs.

### CODE REVIEW

**Comment by mizunashi-mana** [comment]
I fixed codes to detect patch appling.

**Comment by GrahamCampbell** [comment]
I guess the CI is not applying the patches now, which is why the build is failing on macos?

**Comment by mizunashi-mana** [comment]
@GrahamCampbell I think the reason is that PHP <= 5.3 require autoconf <= 2.53, but current autoconf is 2.69.
However, I found this PR is not necessary.

Now, I try to patch https://github.com/php/php-src/pull/3616 using php-build, but php-build don't rebuild `./configure` and I couldn't find doing it.  So, I sent this PR.
But, I found a way to apply the patch; containing `./configure` difference such as `php-5.3.29-64bit-intl.patch`.

**Comment by GrahamCampbell** [comment]
Great, thanks. :)

**Pull request merged**
