### PR TITLE
Removed with-mysql from defaults

### LINKED ISSUE #348: Remove `--with-mysql` from default_configure_options
https://github.com/php-build/php-build/blob/master/share/php-build/default_configure_options#L24 still has `--with-mysql`, which is generating a warning on compilations (I got this right know with PHP 7.0.0):

```
configure: WARNING: unrecognized options: `--with-mysql`
```

As we know that `ext-mysql` was removed since PHP 7+, and for so long time `ext-mysql` is deprecated  I think we should drop it, and let just `--with-mysqli`:

| --- | ext/mysqli | PDO_MySQL | ext/mysql |
| --- | --- | --- | --- |
| PHP version introduced | 5.0 | 5.1 | 2.0 |
| Included with PHP 5.x | Yes | Yes | Yes |
| Included with PHP 7.x | Yes | Yes | No |
| Development status | Active | Active | Maintenance only in 5.x; removed in 7.x |
| Lifecycle | Active | Active | Deprecated in 5.x; removed in 7.x |
| Recommended for new projects | Yes | Yes | No |
| OOP Interface | Yes | Yes | No |
| Procedural Interface | Yes | No | Yes |
| API supports non-blocking, asynchronous queries with mysqlnd | Yes | No | No |
| Persistent Connections | Yes | Yes | Yes |
| API supports Charsets | Yes | Yes | Yes |
| API supports server-side Prepared Statements | Yes | Yes | No |
| API supports client-side Prepared Statements | No | Yes | No |
| API supports Stored Procedures | Yes | Yes | No |
| API supports Multiple Statements | Yes | Most | No |
| API supports Transactions | Yes | Yes | No |
| Transactions can be controlled with SQL | Yes | Yes | Yes |
| Supports all MySQL 5.1+ functionality | Yes | Most | No |

> Table source: http://dev.mysql.com/doc/apis-php/en/apis-php-mysqlinfo.api.choosing.html

### PR DESCRIPTION
**Pull request by ikari7789**
Set `--with-mysql` it in each version's definition prior to 7.0.0 as a `configure_option`.

Fixes #348

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests failing?

**Comment by ikari7789** [comment]
I'm not sure if it's due to my changes though. It seems the OSX tests for PR #425 are also failing as well. Perhaps Travis changed something in regards to OSX?

**Comment by GrahamCampbell** [comment]
I don't like the way this involves modifying so many files to add this configuration option to them. Would be better to automatically apply that based on the definition version, rather than having to add it to each definition.

**Comment by GrahamCampbell** [comment]
In any case, this now needs rebasing now that there are now 3 new definitions committed.

**Comment by ikari7789** [comment]
I finally got around to rebasing this (low priority). Also, I've realized that automatically applying based on the definition version isn't easily possible since a definition file doesn't necessarily need to be named after the version it's installing, but rather it's an alias for a set of build steps for php-build to follow. You could just as easily create a definition file called 'my-fun-php' that could install PHP of any version. The php-build script itself doesn't even have MAJOR/MINOR/PATCH variables for detecting this. You could possibly detect the version I suppose from the extracted package, but that seems like more work than necessary simply to remove the default switch for `--with-mysql`.

**Comment by GrahamCampbell** [comment]
I think this is probably good as is actually. Could you rebase again please, and then I'll merge if the tests are green. :)

Sorry for the hold up on getting this processed.

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Pull request merged**
