### PR TITLE
fix new lines in OpenSSL 1.1.0 patch

### PR DESCRIPTION
**Pull request by smola**
The OpenSSL 1.1.0 patch for PHP 5.6 requires DOS new lines for
ext/openssl/tests/bug66501.phpt to match the original file. Otherwise,
the patch fails to apply to this test file.

This commit fixes the new lines for the patch and modifies
.gitattributes to ensure that patches preserve original new lines.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Are you running Windows? Do you have git configured to checkout PHP using Windows style newlines instead of Unix style?

**Comment by smola** [comment]
@GrahamCampbell Nope. I'm running Linux with no autocrlf set. The cited file actually has DOS new lines in php-src git and tarballs. You can check it in the php-src repo with `git show 19524fc6feb44050bbb70c19717c59864ae4955d`. If you run `phpenv install 5.6.40` you should see the rejected hunk in the build log, even if the build succeeds.

**Comment by smola** [comment]
@GrahamCampbell The [original patch](http://zettasystem.com/PHP-5.6.31-OpenSSL-1.1.0-compatibility-20170801.patch) has the DOS-style new lines for this hunk, but they were probably lost when committing it to this repo.

**Comment by GrahamCampbell** [comment]
Hmm, why is our CI not failing. Are we not covering this?

**Comment by smola** [comment]
Failing patches do not make the build fail:

https://github.com/php-build/php-build/blob/45166ed11a77d5991ed41354dbd5d13095f61ade/bin/php-build#L458-L460

Since this patch fails partially, it would only affect `make test` in some circumstances.

**Comment by GrahamCampbell** [comment]
Can we make failing to apply a patch a loud failure?

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Pull request merged**
