### PR TITLE
Create MAINTAINERS

### PR DESCRIPTION
**Pull request by rogeriopradoj**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not really sure what the point in this is tbh?

**Comment by rogeriopradoj** [comment]
@php-build/collaborators @php-build/owners the idea is to have all the PRs approved for two (or the number we choose) or more of the maintainers in order to keep project consistence better.

That strict policy was already pointed by me and by @CHH in:
- @rogeriopradoj: https://github.com/php-build/php-build/pull/321#issuecomment-154826812
- @CHH: https://github.com/php-build/php-build/pull/322#issuecomment-154881173

The docs of the project is on https://lgtm.co/docs/approvals/ , and it really LGTM!

**Comment by rogeriopradoj** [comment]
@php-build/collaborators @php-build/owners let's do it?

**Comment by henriquemoody** [comment]
The idea is good, but I don't think it's necessary, specially because from
time to time some of us get away from the projects for some reason, but if
there is only one guy interested on keeping the project it will never dies.

I always think that is better apologize than ask for permission, we can
always send a pull request to revert, improve or fix the code we have
merged and it's our duty to be aware of what we have merged.

**Comment by rogeriopradoj** [comment]
:-( @henriquemoody

**Comment by thaJeztah** [comment]
(Sorry, for meddling, just passing by)

It may be good to have some rules that the maintainers should follow. You'd want to avoid a single maintainer taking over a project without other maintainers having a vote. For reference, we're working on additional rules in the docker open source projects; https://github.com/docker/opensource/pull/42

(Existing rules are here; https://github.com/docker/opensource/blob/master/maintainercollector/rules.toml, https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/project/REVIEWING.md, and https://github.com/docker/docker/blob/9739aa056e11661a9637d38c588eeac28470dea7/CONTRIBUTING.md#merge-approval, we're in the process of consolidating those rules for all projects)

**Comment by GrahamCampbell** [comment]
What is a maintainers file going to achieve though? We're all aware of each others existence, and even if we were to forget, GitHub can already list the team members for us.

**Comment by thaJeztah** [comment]
Situation may be different here, but in the docker repositories, people may have write access to a repository, but not be a maintainer. Having write access does not automatically make you a maintainer. For those cases, we're in the process of adding extra checks so that only LGTMs of actual maintainers are counted.

Having a maintainers file can be informative for external contributors, knowing which people to contact, or knowing which person is responsible for "what"

**Comment by GrahamCampbell** [comment]
Just noticed the actual status stuff there. I think this is a really stupid idea. Means we can just quickly add some new PHP versions.

**Comment by henriquemoody** [comment]
I was talking about the _LGTM process_, about the _MAINTAINERS_ file, I'm not against, but I think it's unnecessary as well.

I'm +0 for merging this pull request, and -1 for expect two _LGTM_ on every pull request.

**Comment by GrahamCampbell** [comment]
I think if we can't trust each other not to merge random crap without asking each other first, then what are we even doing here?

**Comment by henriquemoody** [comment]
For me trust is the whole point on giving write permission for someone.

**Comment by GrahamCampbell** [comment]
So why do we need this PR?

**Comment by henriquemoody** [comment]
I think we can keep this pull request to make more obvious who are the project's maintainers, but I disagree with the LGTM process.

**Comment by GrahamCampbell** [comment]
So this is at :+1: :-1: :-1: atm, right?

**Comment by GrahamCampbell** [comment]
That is, as it stands.

**Comment by GrahamCampbell** [comment]
https://github.com/orgs/php-build/people already lists everyone, and is public viewable.

**Pull request closed without merging**
